# Default values for commercialhaskell-com-redirect.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  http:
    name: http
    externalPort: 80
    internalPort: http
  https:
    name: https
    externalPort: 443
    internalPort: https

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/permanent-redirect: "https://github.com/commercialhaskell/commercialhaskell#readme"
  path: /
  hosts:
    - www.commercialhaskell.com
    - commercialhaskell.com
  tls:
    - secretName: commercialhaskell-com-redirect-tls
      hosts:
        - www.commercialhaskell.com
        - commercialhaskell.com

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
